### ISSUE TITLE
Office

### ISSUE THREAD

**Issue by chrisopedia** [thenewtons/decorations#11]
## Measurements

* 11’1” L x 7’10” H (2 walls)
* 10’5” L x 7’10” H (1 wall)

## Task

* [x] hang television
* [x] hang soundbar
* [x] hang mac mini & SuperDrive - rehang, and move to right a bit
* [x] setup dropcam
* [x] setup smart things
    * [x] motion sensors (2)
    * [x] ~~open/closed sensor on door~~
    * [x] open/closed sensor on windows (2)
    * [x] set up rules so that lights turn on when entering room
* [x] touch up paint
* [x] hang paintings
    * [x] Superman
    * [x] Captain America
    * [x] Ralph/PITA
* [x] Hang guitars
    * [x] Bass
    * [x] Electric
    * [x] ~~Acoustic?~~
* [x] set up xbox
* [x] set up backup server
* [x] set up small table to hide server, cables, home automation devices
* [x] install ceiling fan
* [x] install window screens
* [x] repaint ralph frame
* [x] redo the shelves (5)
    * [x] replace hardware
    * [x] replace wood and paint
    * [x] cut out the panel for shelves
* [x] cut out space for beer fridge in bottom drawer
* [ ] Display case for Back to the Future models
* [ ] Display case for PEZ dispensers
    * [ ] set up baseball card backing so they're fastened down
    * [ ] make shelf to get 2 rows (if possible)
* [x] ~~Frame Diploma~~
* [x] get chair
* [x] build desk
* [x] get cooling dog bed
* [ ] bookshelf for closet section
    * [ ] Baseball card collages as the backing
* [ ] install z-wave light switch
* [x] 3 color hue lights
* [x] realign soundbar
* [x] remove the back section of small cabinet to air out drobo
* [x] realign small cabinet to be underneath TV centered
* [x] extend phone cable to allow phone on desk
* [x] clip on fan for server to keep drobo from overheating
* [x] shadow box for legos display
